DELIMITER $$

CREATE TRIGGER stream_date_trigg
    BEFORE INSERT
    ON STREAM FOR EACH ROW
BEGIN

    INSERT INTO DATE_KEEP(D_ID, date_time)
    VALUES(NEW.D_ID,
           FROM_UNIXTIME( UNIX_TIMESTAMP('2010-04-30 14:53:27') + FLOOR(0 + (RAND() * 25920000) ) )
    )
END$$

DELIMITER;